version: "3"

services:
  source:
    build: ./docker/source
    container_name: awr_vue
    working_dir: /var/www/awr
    expose:
      - 9000
    ports:
      - 8080:8080
      - 8000:8000
    restart: always
    volumes:
      - ./front:/var/www/awr

  web:
    build: ./docker/web
    container_name: awr_nginx
    depends_on:
      - source
    ports:
      - 80:80
    restart: always
    volumes:
      - ./front:/var/www/awr
